"""add language to posts

Revision ID: aee78877cc2d
Revises: ee488fcf4ee5
Create Date: 2022-02-16 01:14:29.031883

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aee78877cc2d"
down_revision = "ee488fcf4ee5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post", sa.Column("language", sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post", "language")
    # ### end Alembic commands ###
